on: [push]

name: AzureLoginSample

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:    
      # Install azure-cli
      - uses: elstudio/action-install-azure-cli@v1
      # Now run whatever steps require the `az` command line utility 
      - uses: azure/webapps-deploy@v2
      # for example
      - name: Log in with Azure
        uses: azure/login@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
